version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    timezone: Asia/Singapore
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/webpack"
    versions:
    - 5.0.0
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.0
    - 5.27.0
